/**
 * As minimal as it gets. Exports facilities for connecting to a datastore instance
 * and exposes the raw protobuffer messages for building requests to the datastore's
 * protobuffer API (generated by the [protobuf][1] library).
 *
 * [1][https://github.com/dart-lang/dart-protobuf]
 */
library datastore.protobuf;

export 'src/proto/schema_v1_pb2.dart';
export 'src/connection.dart';